// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using P05Shop.API.Models;

#nullable disable

namespace P05Shop.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231105161415_FilmsMigration")]
    partial class FilmsMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("P06.Shared.Films.Film", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(8,2)");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Films");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Barcode = "2",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Price = 684.749356917454m,
                            ReleaseDate = new DateTime(2022, 11, 24, 20, 43, 45, 338, DateTimeKind.Local).AddTicks(7225),
                            Title = "id"
                        },
                        new
                        {
                            Id = 2,
                            Barcode = "9",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Price = 422.47245453972m,
                            ReleaseDate = new DateTime(2023, 10, 13, 14, 18, 23, 926, DateTimeKind.Local).AddTicks(8307),
                            Title = "harum"
                        },
                        new
                        {
                            Id = 3,
                            Barcode = "0",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Price = 167.353470278137m,
                            ReleaseDate = new DateTime(2023, 9, 27, 9, 41, 12, 447, DateTimeKind.Local).AddTicks(4145),
                            Title = "sint"
                        },
                        new
                        {
                            Id = 4,
                            Barcode = "3",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Price = 191.892937769598m,
                            ReleaseDate = new DateTime(2023, 10, 8, 2, 57, 13, 168, DateTimeKind.Local).AddTicks(2196),
                            Title = "architecto"
                        },
                        new
                        {
                            Id = 5,
                            Barcode = "6",
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Price = 924.811805119185m,
                            ReleaseDate = new DateTime(2022, 12, 15, 18, 13, 5, 493, DateTimeKind.Local).AddTicks(3640),
                            Title = "vero"
                        },
                        new
                        {
                            Id = 6,
                            Barcode = "9",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Price = 711.89268854302m,
                            ReleaseDate = new DateTime(2023, 8, 26, 0, 46, 30, 434, DateTimeKind.Local).AddTicks(5049),
                            Title = "beatae"
                        },
                        new
                        {
                            Id = 7,
                            Barcode = "5",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Price = 947.7514453138m,
                            ReleaseDate = new DateTime(2023, 7, 27, 21, 33, 58, 645, DateTimeKind.Local).AddTicks(7417),
                            Title = "eos"
                        },
                        new
                        {
                            Id = 8,
                            Barcode = "7",
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Price = 22.1707296390881m,
                            ReleaseDate = new DateTime(2023, 6, 18, 4, 51, 10, 639, DateTimeKind.Local).AddTicks(2606),
                            Title = "quidem"
                        },
                        new
                        {
                            Id = 9,
                            Barcode = "0",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Price = 746.682940297147m,
                            ReleaseDate = new DateTime(2022, 11, 6, 13, 20, 46, 274, DateTimeKind.Local).AddTicks(6009),
                            Title = "laboriosam"
                        },
                        new
                        {
                            Id = 10,
                            Barcode = "0",
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Price = 213.803320546077m,
                            ReleaseDate = new DateTime(2023, 11, 2, 12, 1, 29, 733, DateTimeKind.Local).AddTicks(8351),
                            Title = "id"
                        },
                        new
                        {
                            Id = 11,
                            Barcode = "2",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Price = 86.1426076619619m,
                            ReleaseDate = new DateTime(2023, 3, 31, 14, 30, 1, 481, DateTimeKind.Local).AddTicks(4005),
                            Title = "atque"
                        },
                        new
                        {
                            Id = 12,
                            Barcode = "2",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Price = 759.985418102232m,
                            ReleaseDate = new DateTime(2023, 6, 7, 7, 12, 44, 986, DateTimeKind.Local).AddTicks(1615),
                            Title = "dolorum"
                        },
                        new
                        {
                            Id = 13,
                            Barcode = "3",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Price = 538.52330437001m,
                            ReleaseDate = new DateTime(2023, 3, 31, 23, 53, 5, 451, DateTimeKind.Local).AddTicks(4650),
                            Title = "eaque"
                        },
                        new
                        {
                            Id = 14,
                            Barcode = "5",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Price = 57.2601207887102m,
                            ReleaseDate = new DateTime(2022, 12, 4, 22, 39, 20, 471, DateTimeKind.Local).AddTicks(4034),
                            Title = "illum"
                        },
                        new
                        {
                            Id = 15,
                            Barcode = "1",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Price = 495.122995184326m,
                            ReleaseDate = new DateTime(2023, 3, 12, 0, 11, 3, 114, DateTimeKind.Local).AddTicks(5080),
                            Title = "veritatis"
                        },
                        new
                        {
                            Id = 16,
                            Barcode = "8",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Price = 223.045942151475m,
                            ReleaseDate = new DateTime(2022, 11, 17, 21, 24, 11, 344, DateTimeKind.Local).AddTicks(1476),
                            Title = "vero"
                        },
                        new
                        {
                            Id = 17,
                            Barcode = "0",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Price = 476.815506478686m,
                            ReleaseDate = new DateTime(2023, 3, 16, 20, 31, 21, 374, DateTimeKind.Local).AddTicks(2981),
                            Title = "et"
                        },
                        new
                        {
                            Id = 18,
                            Barcode = "5",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Price = 733.06374986659m,
                            ReleaseDate = new DateTime(2023, 9, 28, 17, 31, 7, 713, DateTimeKind.Local).AddTicks(4970),
                            Title = "maxime"
                        },
                        new
                        {
                            Id = 19,
                            Barcode = "9",
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Price = 254.120942065549m,
                            ReleaseDate = new DateTime(2023, 7, 10, 15, 53, 51, 126, DateTimeKind.Local).AddTicks(9696),
                            Title = "eum"
                        },
                        new
                        {
                            Id = 20,
                            Barcode = "9",
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Price = 475.062068794883m,
                            ReleaseDate = new DateTime(2023, 7, 26, 21, 45, 1, 132, DateTimeKind.Local).AddTicks(1099),
                            Title = "ut"
                        },
                        new
                        {
                            Id = 21,
                            Barcode = "9",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Price = 970.636928829196m,
                            ReleaseDate = new DateTime(2023, 3, 17, 22, 9, 10, 817, DateTimeKind.Local).AddTicks(9537),
                            Title = "asperiores"
                        },
                        new
                        {
                            Id = 22,
                            Barcode = "2",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Price = 375.314507679695m,
                            ReleaseDate = new DateTime(2022, 12, 26, 13, 51, 0, 675, DateTimeKind.Local).AddTicks(9846),
                            Title = "corrupti"
                        },
                        new
                        {
                            Id = 23,
                            Barcode = "5",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Price = 751.959149548299m,
                            ReleaseDate = new DateTime(2023, 4, 22, 9, 20, 32, 583, DateTimeKind.Local).AddTicks(3944),
                            Title = "facere"
                        },
                        new
                        {
                            Id = 24,
                            Barcode = "1",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Price = 155.456089345951m,
                            ReleaseDate = new DateTime(2023, 10, 1, 10, 55, 55, 625, DateTimeKind.Local).AddTicks(2204),
                            Title = "aut"
                        },
                        new
                        {
                            Id = 25,
                            Barcode = "6",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Price = 768.439640581347m,
                            ReleaseDate = new DateTime(2023, 9, 23, 19, 52, 53, 851, DateTimeKind.Local).AddTicks(8555),
                            Title = "sint"
                        },
                        new
                        {
                            Id = 26,
                            Barcode = "1",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Price = 985.158759732339m,
                            ReleaseDate = new DateTime(2023, 1, 14, 14, 54, 18, 843, DateTimeKind.Local).AddTicks(7717),
                            Title = "voluptates"
                        },
                        new
                        {
                            Id = 27,
                            Barcode = "6",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Price = 639.781882750234m,
                            ReleaseDate = new DateTime(2023, 8, 10, 12, 31, 25, 84, DateTimeKind.Local).AddTicks(3608),
                            Title = "velit"
                        },
                        new
                        {
                            Id = 28,
                            Barcode = "8",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Price = 677.955690698212m,
                            ReleaseDate = new DateTime(2023, 10, 5, 1, 3, 2, 931, DateTimeKind.Local).AddTicks(9058),
                            Title = "commodi"
                        },
                        new
                        {
                            Id = 29,
                            Barcode = "6",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Price = 376.795993395986m,
                            ReleaseDate = new DateTime(2023, 8, 20, 16, 11, 12, 645, DateTimeKind.Local).AddTicks(5122),
                            Title = "voluptas"
                        },
                        new
                        {
                            Id = 30,
                            Barcode = "5",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Price = 943.967606426202m,
                            ReleaseDate = new DateTime(2023, 10, 17, 22, 30, 10, 476, DateTimeKind.Local).AddTicks(869),
                            Title = "fugit"
                        },
                        new
                        {
                            Id = 31,
                            Barcode = "1",
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Price = 64.2255390939422m,
                            ReleaseDate = new DateTime(2023, 5, 2, 2, 54, 18, 235, DateTimeKind.Local).AddTicks(5616),
                            Title = "dolores"
                        },
                        new
                        {
                            Id = 32,
                            Barcode = "2",
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Price = 742.460550793195m,
                            ReleaseDate = new DateTime(2023, 3, 9, 0, 43, 50, 616, DateTimeKind.Local).AddTicks(5014),
                            Title = "enim"
                        },
                        new
                        {
                            Id = 33,
                            Barcode = "6",
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Price = 297.553123664368m,
                            ReleaseDate = new DateTime(2023, 5, 29, 13, 36, 9, 503, DateTimeKind.Local).AddTicks(3024),
                            Title = "ut"
                        },
                        new
                        {
                            Id = 34,
                            Barcode = "5",
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Price = 147.49753606296m,
                            ReleaseDate = new DateTime(2023, 7, 9, 14, 4, 29, 956, DateTimeKind.Local).AddTicks(6856),
                            Title = "sint"
                        },
                        new
                        {
                            Id = 35,
                            Barcode = "8",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Price = 89.1345175188661m,
                            ReleaseDate = new DateTime(2023, 5, 24, 7, 44, 40, 345, DateTimeKind.Local).AddTicks(1086),
                            Title = "distinctio"
                        },
                        new
                        {
                            Id = 36,
                            Barcode = "2",
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Price = 816.517572267688m,
                            ReleaseDate = new DateTime(2023, 8, 25, 14, 57, 44, 470, DateTimeKind.Local).AddTicks(8913),
                            Title = "corrupti"
                        },
                        new
                        {
                            Id = 37,
                            Barcode = "5",
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Price = 72.624582859047m,
                            ReleaseDate = new DateTime(2023, 10, 4, 20, 21, 57, 952, DateTimeKind.Local).AddTicks(7936),
                            Title = "ipsum"
                        },
                        new
                        {
                            Id = 38,
                            Barcode = "6",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Price = 29.9763303217368m,
                            ReleaseDate = new DateTime(2023, 6, 22, 22, 51, 7, 364, DateTimeKind.Local).AddTicks(6486),
                            Title = "quod"
                        },
                        new
                        {
                            Id = 39,
                            Barcode = "8",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Price = 800.322248479501m,
                            ReleaseDate = new DateTime(2023, 7, 31, 11, 48, 37, 225, DateTimeKind.Local).AddTicks(4624),
                            Title = "culpa"
                        },
                        new
                        {
                            Id = 40,
                            Barcode = "0",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Price = 615.200972841215m,
                            ReleaseDate = new DateTime(2023, 9, 12, 16, 53, 12, 264, DateTimeKind.Local).AddTicks(9125),
                            Title = "ut"
                        },
                        new
                        {
                            Id = 41,
                            Barcode = "1",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Price = 928.988735241344m,
                            ReleaseDate = new DateTime(2023, 1, 25, 11, 13, 54, 90, DateTimeKind.Local).AddTicks(2764),
                            Title = "exercitationem"
                        },
                        new
                        {
                            Id = 42,
                            Barcode = "3",
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Price = 388.689203849383m,
                            ReleaseDate = new DateTime(2023, 7, 15, 6, 16, 16, 195, DateTimeKind.Local).AddTicks(7029),
                            Title = "et"
                        },
                        new
                        {
                            Id = 43,
                            Barcode = "1",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Price = 502.611870216025m,
                            ReleaseDate = new DateTime(2023, 4, 21, 4, 6, 46, 716, DateTimeKind.Local).AddTicks(174),
                            Title = "qui"
                        },
                        new
                        {
                            Id = 44,
                            Barcode = "9",
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Price = 645.556666344198m,
                            ReleaseDate = new DateTime(2023, 7, 1, 22, 28, 36, 283, DateTimeKind.Local).AddTicks(5606),
                            Title = "ratione"
                        },
                        new
                        {
                            Id = 45,
                            Barcode = "3",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Price = 619.502076236299m,
                            ReleaseDate = new DateTime(2023, 9, 24, 16, 57, 42, 836, DateTimeKind.Local).AddTicks(4222),
                            Title = "facere"
                        },
                        new
                        {
                            Id = 46,
                            Barcode = "9",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Price = 424.687753792707m,
                            ReleaseDate = new DateTime(2023, 8, 3, 8, 48, 38, 254, DateTimeKind.Local).AddTicks(6432),
                            Title = "consectetur"
                        },
                        new
                        {
                            Id = 47,
                            Barcode = "4",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Price = 310.46256466278m,
                            ReleaseDate = new DateTime(2023, 2, 5, 13, 8, 56, 198, DateTimeKind.Local).AddTicks(4262),
                            Title = "delectus"
                        },
                        new
                        {
                            Id = 48,
                            Barcode = "5",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Price = 241.00351070706m,
                            ReleaseDate = new DateTime(2023, 2, 12, 18, 45, 35, 33, DateTimeKind.Local).AddTicks(3972),
                            Title = "reprehenderit"
                        },
                        new
                        {
                            Id = 49,
                            Barcode = "2",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Price = 538.22909000061m,
                            ReleaseDate = new DateTime(2023, 10, 23, 6, 56, 42, 421, DateTimeKind.Local).AddTicks(3517),
                            Title = "est"
                        },
                        new
                        {
                            Id = 50,
                            Barcode = "5",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Price = 531.093987403947m,
                            ReleaseDate = new DateTime(2023, 5, 28, 7, 33, 24, 825, DateTimeKind.Local).AddTicks(4626),
                            Title = "voluptatem"
                        });
                });

            modelBuilder.Entity("P06Shop.Shared.Shop.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(8,2)");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Barcode = "3",
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Price = 712.021981759007m,
                            ReleaseDate = new DateTime(2023, 3, 19, 22, 34, 14, 735, DateTimeKind.Local).AddTicks(5145),
                            Title = "Gorgeous Wooden Chair"
                        },
                        new
                        {
                            Id = 2,
                            Barcode = "7",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Price = 839.010165513032m,
                            ReleaseDate = new DateTime(2023, 9, 29, 19, 12, 48, 371, DateTimeKind.Local).AddTicks(7290),
                            Title = "Handcrafted Steel Shoes"
                        },
                        new
                        {
                            Id = 3,
                            Barcode = "1",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Price = 198.083692779804m,
                            ReleaseDate = new DateTime(2023, 1, 18, 14, 6, 31, 644, DateTimeKind.Local).AddTicks(9294),
                            Title = "Handmade Granite Table"
                        },
                        new
                        {
                            Id = 4,
                            Barcode = "1",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Price = 160.643399712929m,
                            ReleaseDate = new DateTime(2023, 8, 20, 2, 20, 2, 4, DateTimeKind.Local).AddTicks(666),
                            Title = "Handmade Wooden Table"
                        },
                        new
                        {
                            Id = 5,
                            Barcode = "0",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Price = 359.887736376788m,
                            ReleaseDate = new DateTime(2023, 2, 20, 3, 38, 13, 733, DateTimeKind.Local).AddTicks(6842),
                            Title = "Intelligent Steel Salad"
                        },
                        new
                        {
                            Id = 6,
                            Barcode = "8",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Price = 181.360829243139m,
                            ReleaseDate = new DateTime(2023, 9, 3, 15, 25, 46, 843, DateTimeKind.Local).AddTicks(4161),
                            Title = "Handcrafted Rubber Bike"
                        },
                        new
                        {
                            Id = 7,
                            Barcode = "1",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Price = 938.297015022625m,
                            ReleaseDate = new DateTime(2023, 4, 4, 14, 37, 59, 253, DateTimeKind.Local).AddTicks(4208),
                            Title = "Unbranded Steel Car"
                        },
                        new
                        {
                            Id = 8,
                            Barcode = "3",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Price = 223.882037785315m,
                            ReleaseDate = new DateTime(2023, 6, 28, 5, 52, 26, 941, DateTimeKind.Local).AddTicks(6428),
                            Title = "Tasty Plastic Cheese"
                        },
                        new
                        {
                            Id = 9,
                            Barcode = "0",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Price = 249.172251003875m,
                            ReleaseDate = new DateTime(2022, 12, 17, 21, 51, 42, 398, DateTimeKind.Local).AddTicks(3892),
                            Title = "Handcrafted Fresh Sausages"
                        },
                        new
                        {
                            Id = 10,
                            Barcode = "1",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Price = 905.322284099796m,
                            ReleaseDate = new DateTime(2023, 10, 9, 13, 33, 51, 859, DateTimeKind.Local).AddTicks(6543),
                            Title = "Fantastic Frozen Gloves"
                        },
                        new
                        {
                            Id = 11,
                            Barcode = "3",
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Price = 842.480734222792m,
                            ReleaseDate = new DateTime(2023, 8, 8, 6, 47, 56, 1, DateTimeKind.Local).AddTicks(3703),
                            Title = "Generic Steel Ball"
                        },
                        new
                        {
                            Id = 12,
                            Barcode = "1",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Price = 928.928430071533m,
                            ReleaseDate = new DateTime(2023, 8, 16, 11, 19, 52, 775, DateTimeKind.Local).AddTicks(2405),
                            Title = "Ergonomic Rubber Car"
                        },
                        new
                        {
                            Id = 13,
                            Barcode = "6",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Price = 706.948686653259m,
                            ReleaseDate = new DateTime(2023, 7, 16, 16, 33, 21, 694, DateTimeKind.Local).AddTicks(8407),
                            Title = "Generic Steel Pizza"
                        },
                        new
                        {
                            Id = 14,
                            Barcode = "3",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Price = 306.262494314584m,
                            ReleaseDate = new DateTime(2023, 1, 10, 5, 46, 0, 182, DateTimeKind.Local).AddTicks(4714),
                            Title = "Small Metal Sausages"
                        },
                        new
                        {
                            Id = 15,
                            Barcode = "2",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Price = 378.222576259273m,
                            ReleaseDate = new DateTime(2023, 7, 31, 22, 51, 53, 212, DateTimeKind.Local).AddTicks(1857),
                            Title = "Fantastic Soft Pants"
                        },
                        new
                        {
                            Id = 16,
                            Barcode = "6",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Price = 461.718092748764m,
                            ReleaseDate = new DateTime(2022, 11, 18, 14, 46, 41, 679, DateTimeKind.Local).AddTicks(706),
                            Title = "Gorgeous Frozen Towels"
                        },
                        new
                        {
                            Id = 17,
                            Barcode = "7",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Price = 126.128098112125m,
                            ReleaseDate = new DateTime(2023, 6, 28, 5, 8, 13, 257, DateTimeKind.Local).AddTicks(187),
                            Title = "Tasty Steel Cheese"
                        },
                        new
                        {
                            Id = 18,
                            Barcode = "8",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Price = 530.970371435383m,
                            ReleaseDate = new DateTime(2023, 6, 25, 6, 50, 54, 616, DateTimeKind.Local).AddTicks(3236),
                            Title = "Gorgeous Granite Cheese"
                        },
                        new
                        {
                            Id = 19,
                            Barcode = "9",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Price = 913.003066283186m,
                            ReleaseDate = new DateTime(2022, 11, 18, 18, 8, 54, 195, DateTimeKind.Local).AddTicks(6605),
                            Title = "Sleek Rubber Chicken"
                        },
                        new
                        {
                            Id = 20,
                            Barcode = "5",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Price = 940.814879371698m,
                            ReleaseDate = new DateTime(2023, 4, 11, 19, 39, 38, 677, DateTimeKind.Local).AddTicks(9846),
                            Title = "Intelligent Wooden Salad"
                        },
                        new
                        {
                            Id = 21,
                            Barcode = "4",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Price = 479.41424090062m,
                            ReleaseDate = new DateTime(2023, 6, 20, 7, 2, 32, 866, DateTimeKind.Local).AddTicks(2219),
                            Title = "Handcrafted Wooden Sausages"
                        },
                        new
                        {
                            Id = 22,
                            Barcode = "7",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Price = 320.499838554068m,
                            ReleaseDate = new DateTime(2023, 1, 31, 2, 29, 55, 135, DateTimeKind.Local).AddTicks(9934),
                            Title = "Sleek Granite Car"
                        },
                        new
                        {
                            Id = 23,
                            Barcode = "6",
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Price = 478.915239043029m,
                            ReleaseDate = new DateTime(2023, 6, 1, 20, 20, 2, 454, DateTimeKind.Local).AddTicks(3497),
                            Title = "Small Wooden Car"
                        },
                        new
                        {
                            Id = 24,
                            Barcode = "2",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Price = 910.785444308438m,
                            ReleaseDate = new DateTime(2023, 7, 3, 12, 56, 21, 683, DateTimeKind.Local).AddTicks(6661),
                            Title = "Sleek Steel Shirt"
                        },
                        new
                        {
                            Id = 25,
                            Barcode = "3",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Price = 802.238750720974m,
                            ReleaseDate = new DateTime(2023, 7, 19, 14, 25, 13, 247, DateTimeKind.Local).AddTicks(3106),
                            Title = "Incredible Frozen Mouse"
                        },
                        new
                        {
                            Id = 26,
                            Barcode = "7",
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Price = 150.818741621831m,
                            ReleaseDate = new DateTime(2023, 5, 14, 8, 1, 33, 370, DateTimeKind.Local).AddTicks(8394),
                            Title = "Incredible Wooden Chair"
                        },
                        new
                        {
                            Id = 27,
                            Barcode = "5",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Price = 721.773541800572m,
                            ReleaseDate = new DateTime(2023, 2, 2, 20, 5, 9, 366, DateTimeKind.Local).AddTicks(9966),
                            Title = "Gorgeous Plastic Chips"
                        },
                        new
                        {
                            Id = 28,
                            Barcode = "5",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Price = 688.245783060904m,
                            ReleaseDate = new DateTime(2023, 4, 27, 22, 31, 4, 478, DateTimeKind.Local).AddTicks(5185),
                            Title = "Incredible Fresh Bacon"
                        },
                        new
                        {
                            Id = 29,
                            Barcode = "7",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Price = 553.558320945389m,
                            ReleaseDate = new DateTime(2023, 7, 21, 9, 1, 58, 471, DateTimeKind.Local).AddTicks(6490),
                            Title = "Incredible Soft Computer"
                        },
                        new
                        {
                            Id = 30,
                            Barcode = "4",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Price = 663.536718269594m,
                            ReleaseDate = new DateTime(2022, 11, 15, 9, 57, 21, 687, DateTimeKind.Local).AddTicks(8274),
                            Title = "Handcrafted Rubber Bike"
                        },
                        new
                        {
                            Id = 31,
                            Barcode = "2",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Price = 922.479030014704m,
                            ReleaseDate = new DateTime(2023, 10, 11, 8, 23, 10, 884, DateTimeKind.Local).AddTicks(6429),
                            Title = "Handcrafted Concrete Tuna"
                        },
                        new
                        {
                            Id = 32,
                            Barcode = "3",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Price = 255.49067058018m,
                            ReleaseDate = new DateTime(2023, 7, 22, 4, 10, 36, 823, DateTimeKind.Local).AddTicks(6857),
                            Title = "Gorgeous Wooden Fish"
                        },
                        new
                        {
                            Id = 33,
                            Barcode = "7",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Price = 955.272407213818m,
                            ReleaseDate = new DateTime(2023, 4, 29, 4, 39, 38, 74, DateTimeKind.Local).AddTicks(2767),
                            Title = "Handcrafted Frozen Keyboard"
                        },
                        new
                        {
                            Id = 34,
                            Barcode = "8",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Price = 151.982358236323m,
                            ReleaseDate = new DateTime(2022, 11, 25, 21, 55, 25, 913, DateTimeKind.Local).AddTicks(361),
                            Title = "Intelligent Plastic Chair"
                        },
                        new
                        {
                            Id = 35,
                            Barcode = "9",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Price = 434.299358334532m,
                            ReleaseDate = new DateTime(2022, 12, 14, 2, 47, 43, 908, DateTimeKind.Local).AddTicks(36),
                            Title = "Unbranded Wooden Pizza"
                        },
                        new
                        {
                            Id = 36,
                            Barcode = "4",
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Price = 57.7988712865854m,
                            ReleaseDate = new DateTime(2023, 1, 2, 21, 21, 41, 441, DateTimeKind.Local).AddTicks(1830),
                            Title = "Gorgeous Rubber Bacon"
                        },
                        new
                        {
                            Id = 37,
                            Barcode = "7",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Price = 883.980300599234m,
                            ReleaseDate = new DateTime(2023, 3, 31, 12, 54, 54, 836, DateTimeKind.Local).AddTicks(9989),
                            Title = "Handcrafted Rubber Shirt"
                        },
                        new
                        {
                            Id = 38,
                            Barcode = "7",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Price = 822.452619476455m,
                            ReleaseDate = new DateTime(2023, 1, 10, 10, 56, 35, 156, DateTimeKind.Local).AddTicks(1360),
                            Title = "Rustic Granite Shoes"
                        },
                        new
                        {
                            Id = 39,
                            Barcode = "7",
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Price = 22.2432652671092m,
                            ReleaseDate = new DateTime(2023, 4, 6, 18, 34, 49, 715, DateTimeKind.Local).AddTicks(6506),
                            Title = "Sleek Granite Chair"
                        },
                        new
                        {
                            Id = 40,
                            Barcode = "2",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Price = 158.364214679396m,
                            ReleaseDate = new DateTime(2023, 6, 24, 15, 21, 6, 339, DateTimeKind.Local).AddTicks(4295),
                            Title = "Incredible Rubber Soap"
                        },
                        new
                        {
                            Id = 41,
                            Barcode = "7",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Price = 533.504530191656m,
                            ReleaseDate = new DateTime(2023, 8, 6, 22, 26, 28, 487, DateTimeKind.Local).AddTicks(6344),
                            Title = "Awesome Soft Fish"
                        },
                        new
                        {
                            Id = 42,
                            Barcode = "8",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Price = 265.709933652407m,
                            ReleaseDate = new DateTime(2023, 7, 29, 9, 37, 27, 917, DateTimeKind.Local).AddTicks(1653),
                            Title = "Intelligent Cotton Tuna"
                        },
                        new
                        {
                            Id = 43,
                            Barcode = "2",
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Price = 294.402654204239m,
                            ReleaseDate = new DateTime(2023, 1, 21, 1, 23, 41, 473, DateTimeKind.Local).AddTicks(629),
                            Title = "Refined Soft Bike"
                        },
                        new
                        {
                            Id = 44,
                            Barcode = "5",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Price = 741.648888164036m,
                            ReleaseDate = new DateTime(2023, 1, 24, 23, 4, 6, 631, DateTimeKind.Local).AddTicks(8256),
                            Title = "Handmade Cotton Bacon"
                        },
                        new
                        {
                            Id = 45,
                            Barcode = "5",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Price = 825.239833488706m,
                            ReleaseDate = new DateTime(2023, 1, 2, 19, 10, 29, 701, DateTimeKind.Local).AddTicks(9773),
                            Title = "Small Soft Tuna"
                        },
                        new
                        {
                            Id = 46,
                            Barcode = "1",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Price = 305.894089151124m,
                            ReleaseDate = new DateTime(2023, 5, 7, 23, 52, 41, 261, DateTimeKind.Local).AddTicks(3306),
                            Title = "Practical Frozen Computer"
                        },
                        new
                        {
                            Id = 47,
                            Barcode = "4",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Price = 778.911179241683m,
                            ReleaseDate = new DateTime(2023, 1, 10, 18, 52, 15, 563, DateTimeKind.Local).AddTicks(6448),
                            Title = "Rustic Wooden Mouse"
                        },
                        new
                        {
                            Id = 48,
                            Barcode = "2",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Price = 318.709401070936m,
                            ReleaseDate = new DateTime(2023, 2, 22, 15, 44, 32, 989, DateTimeKind.Local).AddTicks(6082),
                            Title = "Handcrafted Metal Mouse"
                        },
                        new
                        {
                            Id = 49,
                            Barcode = "6",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Price = 463.195345650052m,
                            ReleaseDate = new DateTime(2023, 4, 7, 20, 26, 36, 591, DateTimeKind.Local).AddTicks(5288),
                            Title = "Handcrafted Rubber Salad"
                        },
                        new
                        {
                            Id = 50,
                            Barcode = "6",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Price = 717.609017980569m,
                            ReleaseDate = new DateTime(2023, 8, 25, 9, 35, 35, 771, DateTimeKind.Local).AddTicks(3966),
                            Title = "Incredible Plastic Shoes"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
