// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using P05Shop.API.Models;

#nullable disable

namespace P05Shop.API.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("P06.Shared.Films.Film", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(8,2)");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Films");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Barcode = "2",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Price = 684.749356917454m,
                            ReleaseDate = new DateTime(2022, 11, 27, 13, 32, 51, 453, DateTimeKind.Local).AddTicks(7816),
                            Title = "id"
                        },
                        new
                        {
                            Id = 2,
                            Barcode = "9",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Price = 422.47245453972m,
                            ReleaseDate = new DateTime(2023, 10, 16, 7, 7, 30, 41, DateTimeKind.Local).AddTicks(8851),
                            Title = "harum"
                        },
                        new
                        {
                            Id = 3,
                            Barcode = "0",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Price = 167.353470278137m,
                            ReleaseDate = new DateTime(2023, 9, 30, 2, 30, 18, 562, DateTimeKind.Local).AddTicks(4677),
                            Title = "sint"
                        },
                        new
                        {
                            Id = 4,
                            Barcode = "3",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Price = 191.892937769598m,
                            ReleaseDate = new DateTime(2023, 10, 10, 19, 46, 19, 283, DateTimeKind.Local).AddTicks(2723),
                            Title = "architecto"
                        },
                        new
                        {
                            Id = 5,
                            Barcode = "6",
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Price = 924.811805119185m,
                            ReleaseDate = new DateTime(2022, 12, 18, 11, 2, 11, 608, DateTimeKind.Local).AddTicks(4105),
                            Title = "vero"
                        },
                        new
                        {
                            Id = 6,
                            Barcode = "9",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Price = 711.89268854302m,
                            ReleaseDate = new DateTime(2023, 8, 28, 17, 35, 36, 549, DateTimeKind.Local).AddTicks(5504),
                            Title = "beatae"
                        },
                        new
                        {
                            Id = 7,
                            Barcode = "5",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Price = 947.7514453138m,
                            ReleaseDate = new DateTime(2023, 7, 30, 14, 23, 4, 760, DateTimeKind.Local).AddTicks(7867),
                            Title = "eos"
                        },
                        new
                        {
                            Id = 8,
                            Barcode = "7",
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Price = 22.1707296390881m,
                            ReleaseDate = new DateTime(2023, 6, 20, 21, 40, 16, 754, DateTimeKind.Local).AddTicks(3083),
                            Title = "quidem"
                        },
                        new
                        {
                            Id = 9,
                            Barcode = "0",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Price = 746.682940297147m,
                            ReleaseDate = new DateTime(2022, 11, 9, 6, 9, 52, 389, DateTimeKind.Local).AddTicks(6483),
                            Title = "laboriosam"
                        },
                        new
                        {
                            Id = 10,
                            Barcode = "0",
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Price = 213.803320546077m,
                            ReleaseDate = new DateTime(2023, 11, 5, 4, 50, 35, 848, DateTimeKind.Local).AddTicks(8819),
                            Title = "id"
                        },
                        new
                        {
                            Id = 11,
                            Barcode = "2",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Price = 86.1426076619619m,
                            ReleaseDate = new DateTime(2023, 4, 3, 7, 19, 7, 596, DateTimeKind.Local).AddTicks(4467),
                            Title = "atque"
                        },
                        new
                        {
                            Id = 12,
                            Barcode = "2",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Price = 759.985418102232m,
                            ReleaseDate = new DateTime(2023, 6, 10, 0, 1, 51, 101, DateTimeKind.Local).AddTicks(2072),
                            Title = "dolorum"
                        },
                        new
                        {
                            Id = 13,
                            Barcode = "3",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Price = 538.52330437001m,
                            ReleaseDate = new DateTime(2023, 4, 3, 16, 42, 11, 566, DateTimeKind.Local).AddTicks(5101),
                            Title = "eaque"
                        },
                        new
                        {
                            Id = 14,
                            Barcode = "5",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Price = 57.2601207887102m,
                            ReleaseDate = new DateTime(2022, 12, 7, 15, 28, 26, 586, DateTimeKind.Local).AddTicks(4480),
                            Title = "illum"
                        },
                        new
                        {
                            Id = 15,
                            Barcode = "1",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Price = 495.122995184326m,
                            ReleaseDate = new DateTime(2023, 3, 14, 17, 0, 9, 229, DateTimeKind.Local).AddTicks(5493),
                            Title = "veritatis"
                        },
                        new
                        {
                            Id = 16,
                            Barcode = "8",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Price = 223.045942151475m,
                            ReleaseDate = new DateTime(2022, 11, 20, 14, 13, 17, 459, DateTimeKind.Local).AddTicks(1882),
                            Title = "vero"
                        },
                        new
                        {
                            Id = 17,
                            Barcode = "0",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Price = 476.815506478686m,
                            ReleaseDate = new DateTime(2023, 3, 19, 13, 20, 27, 489, DateTimeKind.Local).AddTicks(3381),
                            Title = "et"
                        },
                        new
                        {
                            Id = 18,
                            Barcode = "5",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Price = 733.06374986659m,
                            ReleaseDate = new DateTime(2023, 10, 1, 10, 20, 13, 828, DateTimeKind.Local).AddTicks(5390),
                            Title = "maxime"
                        },
                        new
                        {
                            Id = 19,
                            Barcode = "9",
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Price = 254.120942065549m,
                            ReleaseDate = new DateTime(2023, 7, 13, 8, 42, 57, 242, DateTimeKind.Local).AddTicks(111),
                            Title = "eum"
                        },
                        new
                        {
                            Id = 20,
                            Barcode = "9",
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Price = 475.062068794883m,
                            ReleaseDate = new DateTime(2023, 7, 29, 14, 34, 7, 247, DateTimeKind.Local).AddTicks(1510),
                            Title = "ut"
                        },
                        new
                        {
                            Id = 21,
                            Barcode = "9",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Price = 970.636928829196m,
                            ReleaseDate = new DateTime(2023, 3, 20, 14, 58, 16, 932, DateTimeKind.Local).AddTicks(9942),
                            Title = "asperiores"
                        },
                        new
                        {
                            Id = 22,
                            Barcode = "2",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Price = 375.314507679695m,
                            ReleaseDate = new DateTime(2022, 12, 29, 6, 40, 6, 791, DateTimeKind.Local).AddTicks(245),
                            Title = "corrupti"
                        },
                        new
                        {
                            Id = 23,
                            Barcode = "5",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Price = 751.959149548299m,
                            ReleaseDate = new DateTime(2023, 4, 25, 2, 9, 38, 698, DateTimeKind.Local).AddTicks(4337),
                            Title = "facere"
                        },
                        new
                        {
                            Id = 24,
                            Barcode = "1",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Price = 155.456089345951m,
                            ReleaseDate = new DateTime(2023, 10, 4, 3, 45, 1, 740, DateTimeKind.Local).AddTicks(2591),
                            Title = "aut"
                        },
                        new
                        {
                            Id = 25,
                            Barcode = "6",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Price = 768.439640581347m,
                            ReleaseDate = new DateTime(2023, 9, 26, 12, 41, 59, 966, DateTimeKind.Local).AddTicks(8909),
                            Title = "sint"
                        },
                        new
                        {
                            Id = 26,
                            Barcode = "1",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Price = 985.158759732339m,
                            ReleaseDate = new DateTime(2023, 1, 17, 7, 43, 24, 958, DateTimeKind.Local).AddTicks(8063),
                            Title = "voluptates"
                        },
                        new
                        {
                            Id = 27,
                            Barcode = "6",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Price = 639.781882750234m,
                            ReleaseDate = new DateTime(2023, 8, 13, 5, 20, 31, 199, DateTimeKind.Local).AddTicks(3949),
                            Title = "velit"
                        },
                        new
                        {
                            Id = 28,
                            Barcode = "8",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Price = 677.955690698212m,
                            ReleaseDate = new DateTime(2023, 10, 7, 17, 52, 9, 46, DateTimeKind.Local).AddTicks(9418),
                            Title = "commodi"
                        },
                        new
                        {
                            Id = 29,
                            Barcode = "6",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Price = 376.795993395986m,
                            ReleaseDate = new DateTime(2023, 8, 23, 9, 0, 18, 760, DateTimeKind.Local).AddTicks(5476),
                            Title = "voluptas"
                        },
                        new
                        {
                            Id = 30,
                            Barcode = "5",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Price = 943.967606426202m,
                            ReleaseDate = new DateTime(2023, 10, 20, 15, 19, 16, 591, DateTimeKind.Local).AddTicks(1219),
                            Title = "fugit"
                        },
                        new
                        {
                            Id = 31,
                            Barcode = "1",
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Price = 64.2255390939422m,
                            ReleaseDate = new DateTime(2023, 5, 4, 19, 43, 24, 350, DateTimeKind.Local).AddTicks(5960),
                            Title = "dolores"
                        },
                        new
                        {
                            Id = 32,
                            Barcode = "2",
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Price = 742.460550793195m,
                            ReleaseDate = new DateTime(2023, 3, 11, 17, 32, 56, 731, DateTimeKind.Local).AddTicks(5351),
                            Title = "enim"
                        },
                        new
                        {
                            Id = 33,
                            Barcode = "6",
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Price = 297.553123664368m,
                            ReleaseDate = new DateTime(2023, 6, 1, 6, 25, 15, 618, DateTimeKind.Local).AddTicks(3356),
                            Title = "ut"
                        },
                        new
                        {
                            Id = 34,
                            Barcode = "5",
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Price = 147.49753606296m,
                            ReleaseDate = new DateTime(2023, 7, 12, 6, 53, 36, 71, DateTimeKind.Local).AddTicks(7183),
                            Title = "sint"
                        },
                        new
                        {
                            Id = 35,
                            Barcode = "8",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Price = 89.1345175188661m,
                            ReleaseDate = new DateTime(2023, 5, 27, 0, 33, 46, 460, DateTimeKind.Local).AddTicks(1380),
                            Title = "distinctio"
                        },
                        new
                        {
                            Id = 36,
                            Barcode = "2",
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Price = 816.517572267688m,
                            ReleaseDate = new DateTime(2023, 8, 28, 7, 46, 50, 585, DateTimeKind.Local).AddTicks(9199),
                            Title = "corrupti"
                        },
                        new
                        {
                            Id = 37,
                            Barcode = "5",
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Price = 72.624582859047m,
                            ReleaseDate = new DateTime(2023, 10, 7, 13, 11, 4, 67, DateTimeKind.Local).AddTicks(8215),
                            Title = "ipsum"
                        },
                        new
                        {
                            Id = 38,
                            Barcode = "6",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Price = 29.9763303217368m,
                            ReleaseDate = new DateTime(2023, 6, 25, 15, 40, 13, 479, DateTimeKind.Local).AddTicks(6760),
                            Title = "quod"
                        },
                        new
                        {
                            Id = 39,
                            Barcode = "8",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Price = 800.322248479501m,
                            ReleaseDate = new DateTime(2023, 8, 3, 4, 37, 43, 340, DateTimeKind.Local).AddTicks(4913),
                            Title = "culpa"
                        },
                        new
                        {
                            Id = 40,
                            Barcode = "0",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Price = 615.200972841215m,
                            ReleaseDate = new DateTime(2023, 9, 15, 9, 42, 18, 379, DateTimeKind.Local).AddTicks(9410),
                            Title = "ut"
                        },
                        new
                        {
                            Id = 41,
                            Barcode = "1",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Price = 928.988735241344m,
                            ReleaseDate = new DateTime(2023, 1, 28, 4, 3, 0, 205, DateTimeKind.Local).AddTicks(3043),
                            Title = "exercitationem"
                        },
                        new
                        {
                            Id = 42,
                            Barcode = "3",
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Price = 388.689203849383m,
                            ReleaseDate = new DateTime(2023, 7, 17, 23, 5, 22, 310, DateTimeKind.Local).AddTicks(7302),
                            Title = "et"
                        },
                        new
                        {
                            Id = 43,
                            Barcode = "1",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Price = 502.611870216025m,
                            ReleaseDate = new DateTime(2023, 4, 23, 20, 55, 52, 831, DateTimeKind.Local).AddTicks(442),
                            Title = "qui"
                        },
                        new
                        {
                            Id = 44,
                            Barcode = "9",
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Price = 645.556666344198m,
                            ReleaseDate = new DateTime(2023, 7, 4, 15, 17, 42, 398, DateTimeKind.Local).AddTicks(5868),
                            Title = "ratione"
                        },
                        new
                        {
                            Id = 45,
                            Barcode = "3",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Price = 619.502076236299m,
                            ReleaseDate = new DateTime(2023, 9, 27, 9, 46, 48, 951, DateTimeKind.Local).AddTicks(4479),
                            Title = "facere"
                        },
                        new
                        {
                            Id = 46,
                            Barcode = "9",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Price = 424.687753792707m,
                            ReleaseDate = new DateTime(2023, 8, 6, 1, 37, 44, 369, DateTimeKind.Local).AddTicks(6657),
                            Title = "consectetur"
                        },
                        new
                        {
                            Id = 47,
                            Barcode = "4",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Price = 310.46256466278m,
                            ReleaseDate = new DateTime(2023, 2, 8, 5, 58, 2, 313, DateTimeKind.Local).AddTicks(4479),
                            Title = "delectus"
                        },
                        new
                        {
                            Id = 48,
                            Barcode = "5",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Price = 241.00351070706m,
                            ReleaseDate = new DateTime(2023, 2, 15, 11, 34, 41, 148, DateTimeKind.Local).AddTicks(4183),
                            Title = "reprehenderit"
                        },
                        new
                        {
                            Id = 49,
                            Barcode = "2",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Price = 538.22909000061m,
                            ReleaseDate = new DateTime(2023, 10, 25, 23, 45, 48, 536, DateTimeKind.Local).AddTicks(3748),
                            Title = "est"
                        },
                        new
                        {
                            Id = 50,
                            Barcode = "5",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Price = 531.093987403947m,
                            ReleaseDate = new DateTime(2023, 5, 31, 0, 22, 30, 940, DateTimeKind.Local).AddTicks(4855),
                            Title = "voluptatem"
                        });
                });

            modelBuilder.Entity("P06Shop.Shared.Shop.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(8,2)");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Barcode = "3",
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Price = 712.021981759007m,
                            ReleaseDate = new DateTime(2023, 3, 22, 15, 23, 20, 851, DateTimeKind.Local).AddTicks(491),
                            Title = "Gorgeous Wooden Chair"
                        },
                        new
                        {
                            Id = 2,
                            Barcode = "7",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Price = 839.010165513032m,
                            ReleaseDate = new DateTime(2023, 10, 2, 12, 1, 54, 487, DateTimeKind.Local).AddTicks(2586),
                            Title = "Handcrafted Steel Shoes"
                        },
                        new
                        {
                            Id = 3,
                            Barcode = "1",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Price = 198.083692779804m,
                            ReleaseDate = new DateTime(2023, 1, 21, 6, 55, 37, 760, DateTimeKind.Local).AddTicks(4585),
                            Title = "Handmade Granite Table"
                        },
                        new
                        {
                            Id = 4,
                            Barcode = "1",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Price = 160.643399712929m,
                            ReleaseDate = new DateTime(2023, 8, 22, 19, 9, 8, 119, DateTimeKind.Local).AddTicks(5952),
                            Title = "Handmade Wooden Table"
                        },
                        new
                        {
                            Id = 5,
                            Barcode = "0",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Price = 359.887736376788m,
                            ReleaseDate = new DateTime(2023, 2, 22, 20, 27, 19, 849, DateTimeKind.Local).AddTicks(2124),
                            Title = "Intelligent Steel Salad"
                        },
                        new
                        {
                            Id = 6,
                            Barcode = "8",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Price = 181.360829243139m,
                            ReleaseDate = new DateTime(2023, 9, 6, 8, 14, 52, 958, DateTimeKind.Local).AddTicks(9396),
                            Title = "Handcrafted Rubber Bike"
                        },
                        new
                        {
                            Id = 7,
                            Barcode = "1",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Price = 938.297015022625m,
                            ReleaseDate = new DateTime(2023, 4, 7, 7, 27, 5, 368, DateTimeKind.Local).AddTicks(9434),
                            Title = "Unbranded Steel Car"
                        },
                        new
                        {
                            Id = 8,
                            Barcode = "3",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Price = 223.882037785315m,
                            ReleaseDate = new DateTime(2023, 6, 30, 22, 41, 33, 57, DateTimeKind.Local).AddTicks(1694),
                            Title = "Tasty Plastic Cheese"
                        },
                        new
                        {
                            Id = 9,
                            Barcode = "0",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Price = 249.172251003875m,
                            ReleaseDate = new DateTime(2022, 12, 20, 14, 40, 48, 513, DateTimeKind.Local).AddTicks(9156),
                            Title = "Handcrafted Fresh Sausages"
                        },
                        new
                        {
                            Id = 10,
                            Barcode = "1",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Price = 905.322284099796m,
                            ReleaseDate = new DateTime(2023, 10, 12, 6, 22, 57, 975, DateTimeKind.Local).AddTicks(1800),
                            Title = "Fantastic Frozen Gloves"
                        },
                        new
                        {
                            Id = 11,
                            Barcode = "3",
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Price = 842.480734222792m,
                            ReleaseDate = new DateTime(2023, 8, 10, 23, 37, 2, 116, DateTimeKind.Local).AddTicks(8951),
                            Title = "Generic Steel Ball"
                        },
                        new
                        {
                            Id = 12,
                            Barcode = "1",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Price = 928.928430071533m,
                            ReleaseDate = new DateTime(2023, 8, 19, 4, 8, 58, 890, DateTimeKind.Local).AddTicks(7645),
                            Title = "Ergonomic Rubber Car"
                        },
                        new
                        {
                            Id = 13,
                            Barcode = "6",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Price = 706.948686653259m,
                            ReleaseDate = new DateTime(2023, 7, 19, 9, 22, 27, 810, DateTimeKind.Local).AddTicks(3615),
                            Title = "Generic Steel Pizza"
                        },
                        new
                        {
                            Id = 14,
                            Barcode = "3",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Price = 306.262494314584m,
                            ReleaseDate = new DateTime(2023, 1, 12, 22, 35, 6, 297, DateTimeKind.Local).AddTicks(9914),
                            Title = "Small Metal Sausages"
                        },
                        new
                        {
                            Id = 15,
                            Barcode = "2",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Price = 378.222576259273m,
                            ReleaseDate = new DateTime(2023, 8, 3, 15, 40, 59, 327, DateTimeKind.Local).AddTicks(7077),
                            Title = "Fantastic Soft Pants"
                        },
                        new
                        {
                            Id = 16,
                            Barcode = "6",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Price = 461.718092748764m,
                            ReleaseDate = new DateTime(2022, 11, 21, 7, 35, 47, 794, DateTimeKind.Local).AddTicks(5920),
                            Title = "Gorgeous Frozen Towels"
                        },
                        new
                        {
                            Id = 17,
                            Barcode = "7",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Price = 126.128098112125m,
                            ReleaseDate = new DateTime(2023, 6, 30, 21, 57, 19, 372, DateTimeKind.Local).AddTicks(5394),
                            Title = "Tasty Steel Cheese"
                        },
                        new
                        {
                            Id = 18,
                            Barcode = "8",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Price = 530.970371435383m,
                            ReleaseDate = new DateTime(2023, 6, 27, 23, 40, 0, 731, DateTimeKind.Local).AddTicks(8435),
                            Title = "Gorgeous Granite Cheese"
                        },
                        new
                        {
                            Id = 19,
                            Barcode = "9",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Price = 913.003066283186m,
                            ReleaseDate = new DateTime(2022, 11, 21, 10, 58, 0, 311, DateTimeKind.Local).AddTicks(1771),
                            Title = "Sleek Rubber Chicken"
                        },
                        new
                        {
                            Id = 20,
                            Barcode = "5",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Price = 940.814879371698m,
                            ReleaseDate = new DateTime(2023, 4, 14, 12, 28, 44, 793, DateTimeKind.Local).AddTicks(5001),
                            Title = "Intelligent Wooden Salad"
                        },
                        new
                        {
                            Id = 21,
                            Barcode = "4",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Price = 479.41424090062m,
                            ReleaseDate = new DateTime(2023, 6, 22, 23, 51, 38, 981, DateTimeKind.Local).AddTicks(7393),
                            Title = "Handcrafted Wooden Sausages"
                        },
                        new
                        {
                            Id = 22,
                            Barcode = "7",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Price = 320.499838554068m,
                            ReleaseDate = new DateTime(2023, 2, 2, 19, 19, 1, 251, DateTimeKind.Local).AddTicks(5102),
                            Title = "Sleek Granite Car"
                        },
                        new
                        {
                            Id = 23,
                            Barcode = "6",
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Price = 478.915239043029m,
                            ReleaseDate = new DateTime(2023, 6, 4, 13, 9, 8, 569, DateTimeKind.Local).AddTicks(8655),
                            Title = "Small Wooden Car"
                        },
                        new
                        {
                            Id = 24,
                            Barcode = "2",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Price = 910.785444308438m,
                            ReleaseDate = new DateTime(2023, 7, 6, 5, 45, 27, 799, DateTimeKind.Local).AddTicks(1812),
                            Title = "Sleek Steel Shirt"
                        },
                        new
                        {
                            Id = 25,
                            Barcode = "3",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Price = 802.238750720974m,
                            ReleaseDate = new DateTime(2023, 7, 22, 7, 14, 19, 362, DateTimeKind.Local).AddTicks(8252),
                            Title = "Incredible Frozen Mouse"
                        },
                        new
                        {
                            Id = 26,
                            Barcode = "7",
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Price = 150.818741621831m,
                            ReleaseDate = new DateTime(2023, 5, 17, 0, 50, 39, 486, DateTimeKind.Local).AddTicks(3509),
                            Title = "Incredible Wooden Chair"
                        },
                        new
                        {
                            Id = 27,
                            Barcode = "5",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Price = 721.773541800572m,
                            ReleaseDate = new DateTime(2023, 2, 5, 12, 54, 15, 482, DateTimeKind.Local).AddTicks(5069),
                            Title = "Gorgeous Plastic Chips"
                        },
                        new
                        {
                            Id = 28,
                            Barcode = "5",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Price = 688.245783060904m,
                            ReleaseDate = new DateTime(2023, 4, 30, 15, 20, 10, 594, DateTimeKind.Local).AddTicks(308),
                            Title = "Incredible Fresh Bacon"
                        },
                        new
                        {
                            Id = 29,
                            Barcode = "7",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Price = 553.558320945389m,
                            ReleaseDate = new DateTime(2023, 7, 24, 1, 51, 4, 587, DateTimeKind.Local).AddTicks(1605),
                            Title = "Incredible Soft Computer"
                        },
                        new
                        {
                            Id = 30,
                            Barcode = "4",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Price = 663.536718269594m,
                            ReleaseDate = new DateTime(2022, 11, 18, 2, 46, 27, 803, DateTimeKind.Local).AddTicks(3382),
                            Title = "Handcrafted Rubber Bike"
                        },
                        new
                        {
                            Id = 31,
                            Barcode = "2",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Price = 922.479030014704m,
                            ReleaseDate = new DateTime(2023, 10, 14, 1, 12, 17, 0, DateTimeKind.Local).AddTicks(1527),
                            Title = "Handcrafted Concrete Tuna"
                        },
                        new
                        {
                            Id = 32,
                            Barcode = "3",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Price = 255.49067058018m,
                            ReleaseDate = new DateTime(2023, 7, 24, 20, 59, 42, 939, DateTimeKind.Local).AddTicks(1949),
                            Title = "Gorgeous Wooden Fish"
                        },
                        new
                        {
                            Id = 33,
                            Barcode = "7",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Price = 955.272407213818m,
                            ReleaseDate = new DateTime(2023, 5, 1, 21, 28, 44, 189, DateTimeKind.Local).AddTicks(7826),
                            Title = "Handcrafted Frozen Keyboard"
                        },
                        new
                        {
                            Id = 34,
                            Barcode = "8",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Price = 151.982358236323m,
                            ReleaseDate = new DateTime(2022, 11, 28, 14, 44, 32, 28, DateTimeKind.Local).AddTicks(5412),
                            Title = "Intelligent Plastic Chair"
                        },
                        new
                        {
                            Id = 35,
                            Barcode = "9",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Price = 434.299358334532m,
                            ReleaseDate = new DateTime(2022, 12, 16, 19, 36, 50, 23, DateTimeKind.Local).AddTicks(5105),
                            Title = "Unbranded Wooden Pizza"
                        },
                        new
                        {
                            Id = 36,
                            Barcode = "4",
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Price = 57.7988712865854m,
                            ReleaseDate = new DateTime(2023, 1, 5, 14, 10, 47, 556, DateTimeKind.Local).AddTicks(6893),
                            Title = "Gorgeous Rubber Bacon"
                        },
                        new
                        {
                            Id = 37,
                            Barcode = "7",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Price = 883.980300599234m,
                            ReleaseDate = new DateTime(2023, 4, 3, 5, 44, 0, 952, DateTimeKind.Local).AddTicks(5045),
                            Title = "Handcrafted Rubber Shirt"
                        },
                        new
                        {
                            Id = 38,
                            Barcode = "7",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Price = 822.452619476455m,
                            ReleaseDate = new DateTime(2023, 1, 13, 3, 45, 41, 271, DateTimeKind.Local).AddTicks(6409),
                            Title = "Rustic Granite Shoes"
                        },
                        new
                        {
                            Id = 39,
                            Barcode = "7",
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Price = 22.2432652671092m,
                            ReleaseDate = new DateTime(2023, 4, 9, 11, 23, 55, 831, DateTimeKind.Local).AddTicks(1548),
                            Title = "Sleek Granite Chair"
                        },
                        new
                        {
                            Id = 40,
                            Barcode = "2",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Price = 158.364214679396m,
                            ReleaseDate = new DateTime(2023, 6, 27, 8, 10, 12, 454, DateTimeKind.Local).AddTicks(9304),
                            Title = "Incredible Rubber Soap"
                        },
                        new
                        {
                            Id = 41,
                            Barcode = "7",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Price = 533.504530191656m,
                            ReleaseDate = new DateTime(2023, 8, 9, 15, 15, 34, 603, DateTimeKind.Local).AddTicks(1345),
                            Title = "Awesome Soft Fish"
                        },
                        new
                        {
                            Id = 42,
                            Barcode = "8",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Price = 265.709933652407m,
                            ReleaseDate = new DateTime(2023, 8, 1, 2, 26, 34, 32, DateTimeKind.Local).AddTicks(6673),
                            Title = "Intelligent Cotton Tuna"
                        },
                        new
                        {
                            Id = 43,
                            Barcode = "2",
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Price = 294.402654204239m,
                            ReleaseDate = new DateTime(2023, 1, 23, 18, 12, 47, 588, DateTimeKind.Local).AddTicks(5643),
                            Title = "Refined Soft Bike"
                        },
                        new
                        {
                            Id = 44,
                            Barcode = "5",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Price = 741.648888164036m,
                            ReleaseDate = new DateTime(2023, 1, 27, 15, 53, 12, 747, DateTimeKind.Local).AddTicks(3264),
                            Title = "Handmade Cotton Bacon"
                        },
                        new
                        {
                            Id = 45,
                            Barcode = "5",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Price = 825.239833488706m,
                            ReleaseDate = new DateTime(2023, 1, 5, 11, 59, 35, 817, DateTimeKind.Local).AddTicks(4774),
                            Title = "Small Soft Tuna"
                        },
                        new
                        {
                            Id = 46,
                            Barcode = "1",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Price = 305.894089151124m,
                            ReleaseDate = new DateTime(2023, 5, 10, 16, 41, 47, 376, DateTimeKind.Local).AddTicks(8274),
                            Title = "Practical Frozen Computer"
                        },
                        new
                        {
                            Id = 47,
                            Barcode = "4",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Price = 778.911179241683m,
                            ReleaseDate = new DateTime(2023, 1, 13, 11, 41, 21, 679, DateTimeKind.Local).AddTicks(1408),
                            Title = "Rustic Wooden Mouse"
                        },
                        new
                        {
                            Id = 48,
                            Barcode = "2",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Price = 318.709401070936m,
                            ReleaseDate = new DateTime(2023, 2, 25, 8, 33, 39, 105, DateTimeKind.Local).AddTicks(1059),
                            Title = "Handcrafted Metal Mouse"
                        },
                        new
                        {
                            Id = 49,
                            Barcode = "6",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Price = 463.195345650052m,
                            ReleaseDate = new DateTime(2023, 4, 10, 13, 15, 42, 707, DateTimeKind.Local).AddTicks(261),
                            Title = "Handcrafted Rubber Salad"
                        },
                        new
                        {
                            Id = 50,
                            Barcode = "6",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Price = 717.609017980569m,
                            ReleaseDate = new DateTime(2023, 8, 28, 2, 24, 41, 886, DateTimeKind.Local).AddTicks(8933),
                            Title = "Incredible Plastic Shoes"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
